### ISSUE TITLE
CI: IPFS link as a comment is broken, CID is now absent

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-account#108]
We observed two error messages.

Relevant code: https://github.com/aleph-im/aleph-account/blob/main/upload_build.py#L36
No new version of the dependency `aioipfs` has been published for a while.
The cause of the issue is probably with the IPFS servers ?

```
Successfully installed aiofiles-23.1.0 aiohttp-3.8.4 aioipfs-0.6.3 aiosignal-1.3.1 async-timeout-4.0.2 base58-2.1.1 charset-normalizer-3.1.0 frozenlist-1.3.3 morphys-1.0 multiaddr-0.0.9 multidict-6.0.4 netaddr-0.8.0 py-multibase-1.0.3 py-multicodec-0.2.1 py-multiformats-cid-0.4.4 py-multihash-2.0.1 python-baseconv-1.2.2 varint-1.0.2 yarl-1.9.2
Qmcs8ScbccMV972dbRcWM1nVL6Qg9hyhzcWhTCeu1oBiqY
Could not read JSON object: Extra data: line 1 column 5 (char 4)
Traceback (most recent call last):
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 57, in <module>
    main()
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 52, in main
    print(asyncio.run(publish_site(Multiaddr("/dns6/ipfs-2.aleph.im/tcp/443/https"))))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 47, in publish_site
    cid = await upload_site(files=[path], multiaddr=multiaddr)
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 38, in upload_site
    return cid or raise_no_cid()
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 24, in raise_no_cid
    raise ValueError("Could not obtain a CID")
ValueError: Could not obtain a CID
```

```
Successfully installed aiofiles-23.1.0 aiohttp-3.8.4 aioipfs-0.6.3 aiosignal-1.3.1 async-timeout-4.0.2 base58-2.1.1 charset-normalizer-3.1.0 frozenlist-1.3.3 morphys-1.0 multiaddr-0.0.9 multidict-6.0.4 netaddr-0.8.0 py-multibase-1.0.3 py-multicodec-0.2.1 py-multiformats-cid-0.4.4 py-multihash-2.0.1 python-baseconv-1.2.2 varint-1.0.2 yarl-1.9.2
Could not read JSON object: Extra data: line 1 column 5 (char 4)
Traceback (most recent call last):
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 57, in <module>
    main()
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 52, in main
    print(asyncio.run(publish_site(Multiaddr("/dns6/ipfs-2.aleph.im/tcp/443/https"))))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 47, in publish_site
    cid = await upload_site(files=[path], multiaddr=multiaddr)
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 38, in upload_site
    return cid or raise_no_cid()
  File "/home/runner/work/aleph-account/aleph-account/./upload_build.py", line 24, in raise_no_cid
    raise ValueError("Could not obtain a CID")
ValueError: Could not obtain a CID
Error: Process completed with exit code 1.
```

**Comment by aliel** [comment]
Fixed
